
seed: 42

paths:

  # Required
  input_folder: data/raw
  output_folder: results/masks
  panel_file: data/panels/ws_panel.csv

  # Non-required: defaults exist
  mask_metadata_folder: results/mask_metadata
  mask_qc_folder: results/mask_qc

preprocessing:

  # Non-required: defaults exist
  toggles:
    apply_background_stain_removal: true
    apply_hot_pixel_removal: true
    apply_striping_removal: true
    apply_denoising: false
    apply_background_subtraction: false
    apply_winsorization: true
    apply_min_max_scaling: true

  rgb_markers:
    - pan_cytokeratin
    - cd45
    - col1a2

  # Non-required: defaults exist
  background_stains: 
    - pnad

  hot_pixel:
    window_size: 3
    z_score_threshold: 6

  striping:
    direction: column
    size: 5

  denoising:
    cofactor: 10

  background_subtraction:
    percentile: 2.0

  winsorization:
    limits: [0.005, 0.005]


tissue_mask:

  # Required
  mask_generation_markers: 
    - pan_cytokeratin
    - vimentin
    - col1a2
    - fibronectin
    - tenacin
    - cd45
    - acta2
    - fap
    - cd31

  # Non-required: defaults exist
  min_tissue_threshold: 0
  small_object_threshold: 50
  small_hole_threshold: 50

  rgb_markers:
    - pan_cytokeratin
    - cd45
    - col1a2
  
