
# ==========| General |========================================================

# Required fields
seed: 42
input_folder: data/raw
panel_file: data/panels/ws_panel.csv
id_mapping_file: data/id_mappings/id_mapping.csv

# ==========| Preprocessing |==================================================

# Not required, defaults provided: only if preprocessing is enabled
preprocessing:

  toggles:
    apply_background_stain_removal: true
    apply_hot_pixel_removal: true
    apply_striping_removal: true
    apply_denoising: false
    apply_background_subtraction: false
    apply_winsorization: true
    apply_min_max_scaling: true

  background_stains: 
    - pnad

  hot_pixel:
    window_size: 3
    z_score_threshold: 6

  striping:
    direction: column
    size: 5

  denoising:
    cofactor: 10

  background_subtraction:
    percentile: 2.0

  winsorization:
    limits: [0.005, 0.005]

# ==========| Tissue Mask |====================================================

tissue_mask:

  # Required
  mask_folder: results/tissue_masks/masks

  # Not required, defaults provided: only required when metadata/QC are enabled
  metadata_folder: results/tissue_masks/metadata
  qc_folder: results/tissue_masks/qc

  # Not required: can be left empty and full panel will be used
  mask_generation_markers: 
    - pan_cytokeratin
    - vimentin
    - col1a2
    - fibronectin
    - tenacin
    - cd45
    - acta2
    - fap
    - cd31

  # Not required, defaults provided: only if functions are toggled
  min_tissue_threshold: 0
  small_object_threshold: 50
  small_hole_threshold: 50

  # Not required: only if QC plots are enabled
  rgb_markers:
    - pan_cytokeratin
    - cd45
    - col1a2
  
# ==========| Patch Extraction |===============================================
  
patch_extraction:

  # Required
  patch_folder: results/patch_extraction/patches.zarr
  mask_folder: results/tissue_masks/masks
  patch_size: [128, 128]
  stride: 0.25
  min_tissue_coverage: 0.50
