
# ==========| General |========================================================

# Required fields
seed: 
input_folder: 
panel_file: 
id_mapping_file: 

# ==========| Preprocessing |==================================================

# Not required, defaults provided: only if preprocessing is enabled
preprocessing:

  toggles:
    apply_background_stain_removal: 
    apply_hot_pixel_removal: 
    apply_striping_removal: 
    apply_denoising: false
    apply_background_subtraction: 
    apply_winsorization: 
    apply_min_max_scaling: 

  background_stains: 

  hot_pixel:
    window_size: 
    z_score_threshold: 

  striping:
    direction: 
    size: 

  denoising:
    cofactor: 

  background_subtraction:
    percentile: 

  winsorization:
    limits: 

# ==========| Tissue Mask |====================================================

# Required
  mask_folder: 

  # Not required, defaults provided: only required when metadata/QC are enabled
  metadata_folder: 
  qc_folder: 

  # Not required: can be left empty and full panel will be used
  mask_generation_markers: 

  # Not required, defaults provided: only if functions are toggled
  min_tissue_threshold: 
  small_object_threshold: 
  small_hole_threshold:

  # Not required: only if QC plots are enabled
  rgb_markers:

# ==========| Patch Extraction |===============================================

patch_extraction:

  # Required
  patch_folder: 
  mask_folder: 
  patch_size: 
  stride: 
  min_tissue_coverage: 